### ISSUE TITLE
Edits page loads sporadically

### ISSUE THREAD

**Issue by ahinz** [OpenTreeMap/otm-core#1818]
Sometimes loads, sometimes 502 (50%):
https://www.opentreemap.org/edmonton/edits/

Almost never loads:
https://www.opentreemap.org/edmonton/edits/?page=100

Really never loads:
https://www.opentreemap.org/edmonton/edits/?page=200

**Comment by maurizi** [comment]
Helpful blog article about ways to speed up pagination: https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/

I think we would want to use what it describes as "Keyset pagination" - on each edits page, we would record the lowest `audit.id` and use it as a page parameter for the "Next" button, and then future queries would add a `WHERE audit.id < prev_page_lowest_id` clause, instead of the `OFFSET` that is currently added by slicing the `QuerySet`
