### ISSUE TITLE
Add support for importing multichoice fields

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2383]
- Define how multiple choices for a single field should be encoded in the CSV
- Properly handle validation and correcting values through the UI

**Comment by steventlamb** [comment]
This could be painful. Do we have a strong use case for this, and for doing it robustly? Or is it that we just don't want imports to crash for instances that have multichoice fields?

If possible, I think we should continue our precedent of dropping down to supporting multichoice fields 
just like single-choice fields. This would mean only allowing the importation and correction of single values. Obviously this is the quick fix, but maybe it is the adequate fix.

Second to that, I think we should store and validate them as json arrays. This would be similar to how they are implemented on the model. Ideally we would require the user to edit them as json arrays in the UI. We can't really use the actual widget in the UI, because it doesn't allow editing incorrect values. Our choices fall down to structured text (json arrays) or a new tabular widget. The latter would be much more difficult.

**Comment by jmorrison1847** [comment]
The use case is for uploads like this one (See the attached file).
[Multi-Field-Demo.xlsx](https://github.com/OpenTreeMap/otm-core/files/57114/Multi-Field-Demo.xlsx)

There are three "Observe" fields (Observe, Observe2, Observe3). Each has an identical dropdown menu, and it's their way of hacking a multi-choice field for 1, 2, or 3 options. It would be great to be able to upload this as a single column or field. I would say it's relatively uncommon, but definitely a real use case especially when people are marking work to be done (e.g. "hazard branch and buried root flare")
