### ISSUE TITLE
Add rain garden / bioswale eco backend

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2647]
Annual rainfall x area of polygon x constant number = Annual stormwater diverted

Rainfall and constant are instance manager supplied values. Hard code until the UI is ready.

**Comment by RickMohr** [comment]
We have a growing collection of fields attached to a map feature type. Current fields:
* class name
* singular display name
* plural display name

New fields:
* should display ecobenefits
* percent stormwater diverted

Currently the fields are stored under two separate keys of `instance.config`:
* `map_feature_types`
* `terminology`

I propose that we combine these fields in a single dict. Defaults would be stored on the `MapFeature` subclass (as today with [`_terminology`](https://github.com/OpenTreeMap/otm-core/blob/8de1867f0af9be3e6570c6a48d19cda4f6cfde45/opentreemap/stormwater/models.py#L78)) with overrides stored on `instance.config.map_feature_types`.

For example, today the `Bioswale` class has a `_terminology` property:
```py
    _terminology = {
        'singular': 'Rain garden',
        'plural': 'Rain gardens'
    }
```
That would be replaced by a `default_config` property:
```py
    default_config = {
        'singular': 'Bioswale',
        'plural': 'Bioswales',
        'should_show_eco': True,
        'diversion_rate': 0.95
    }
```
`instance.config.map_feature_types` would become a dict instead of a list. For example, if you enable Bioswales for an instance and decide not to display ecobenefits, `instance.config.map_feature_types` would be:
```json
{
    "Bioswale": {
        "should_show_eco": false,
    }
}
```

**Comment by jwalgran** [comment]
This looks like a good reorganization, and it is better to do this now, while there are not a lot of features to migrate. To keep it simple I would assume that if I turn off eco

```json
{
    "Bioswale": {
        "should_show_eco": false
    }
}
```

then turn it back on, I would end up with

```json
{
    "Bioswale": {
        "should_show_eco": true
    }
}
```

Is that what you were thinking?

**Comment by RickMohr** [comment]
That is certainly simplest. It's not as nice for the UI because removing a map feature loses your overrides. But that's probably OK since map feature types are rarely if ever removed.

**Comment by RickMohr** [comment]
I am now questioning the wisdom of the above proposed change. Info for map feature types would end up in one place instead of several, but info for terminology would end up in several places instead of one. (Currently, `instance.config.terms` handles alternate terms for map feature types, "Resource", and model names like "Tree" and "Photo" that need translations but aren't map feature types.)

Also, part of my goal was to simplify editing on the "Green Infrastructure" management page. But having now been in that code I think it will be simpler to leave it as-is and store the additional map feature fields in a new  `instance.config.map_feature_config` property.

Even though I've invested some time implementing the above proposal I think going forward it will be faster and less destabilizing to take a similar but simpler approach.

For example, the `Bioswale` class would have a `default_config` property:
```py
    default_config = {
        'should_show_eco': True,
        'diversion_rate': 0.95
    }
```
If you enable Bioswales for an instance and decide not to display ecobenefits, `instance.config.map_feature_config` would be:
```json
{
    "Bioswale": {
        "should_show_eco": false
    }
}
```
