### ISSUE TITLE
Spelling out units (instead of using abbreviation) causes layout problems

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2711]
Because we're now showing "inches" instead of "in" there's not enough room to enter tree diameter in a non-full-width browser:

![image](https://cloud.githubusercontent.com/assets/2162993/17675415/b30962ee-62f7-11e6-820a-8ce83be3289e.png)

Why did we suddenly decide to change that presentation design?

**Comment by maurizi** [comment]
The change was made in https://github.com/OpenTreeMap/otm-core/pull/2697 because with the existing system, we were using internal `dict` keys to display items, which caused the unit for drainage area to display as `sq_m`.

We were also being inconsistent with unit display, showing "feet" in the sidebar, but "ft" on the field row.

The layout problems are a concern though.  Perhaps we should explicitly use abbreviations everywhere? Or try and change the design for the diameter calculator to fit the longer unit names?

**Comment by jwalgran** [comment]
I put this in a new 2.11.0 milestone because I think we need to fix the layout before we ship.

Adding a dictionary of unit keys to abbreviations (or incorporating that mapping into an existing dictionary) seems like the most straightforward solution.

**Comment by dboyer** [comment]
Agreed we need to fix this before the next release. Adding to priority backlog.
