### ISSUE TITLE
Diameter warning limits space for diameter field

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2754]
Tested in staging on Chrome. See attached screenshot. It's hard to type in a diameter since the warning message limits the space for the diameter field to less than one character.
![otm_detail_page_error](https://cloud.githubusercontent.com/assets/516764/18135694/bdfa9e68-6f70-11e6-9ba2-9bf2f5f42860.png)

**Comment by RobinIsTheBird** [comment]
@lederer How do you suggest we display the warning? And should we change the position of all the warnings?

**Comment by RobinIsTheBird** [comment]
@lederer , I know we talked about putting the message below the label, but it turns out to be easier to make it a separate row with a colspan="2" cell. How does this look to you?

![treedetailerrormessage](https://cloud.githubusercontent.com/assets/1473263/18281148/c9de90a0-7429-11e6-9a69-84dc13130138.png)

**Comment by lederer** [comment]
+1 I'll take it.
