### ISSUE TITLE
Cannot move tree as part of quick edit

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/otm-core#2870]
Tested in Chrome 

1. Added a tree
2. Moved tree's location on the tree detail page. Location updated correctly.
3. Returned to map page and selected the tree dot
4. Clicked Quick Edit
5. The "Move Tree" button was grayed out and hover text said "Editing a plot's location is not available to all users"

I'm the map creator and an admin and have full write access to all fields according to the Roles page.

**Comment by dboyer** [comment]
I can now edit the tree's location from the quick edit screen as an admin but not user with the public role. I can edit the tree's location as a public user from the detail page.

I changed the public role setting to have full write access to the address, city, and postal code fields. After that, I was able to save location changes using quick edit.

**Comment by jwalgran** [comment]
Deb was able to reproduce the issue on her test map, but I had trouble recreating it on a new test map of my own.

I created a new map and added a tree, then switched to a user in the Public role for that map. I was unable to click Quick Edit on the map or Edit on the detail page because the public role does not have any write access by default.

When I made address fields editable, I was able to Quick Edit move the planting site on the map and Edit move the planting site on the detail page.

**Comment by RobinIsTheBird** [comment]
@jwalgran, may I take this issue back?

**Comment by RobinIsTheBird** [comment]
@dboyer and @jwalgran,

I haven't been able to reproduce the problem, but do have a few thoughts on it:

1. It is necessary to have Write Access to the Planting Site Address field in order to move a planting site at all. Currently, the Move buttons are enabled even when Address is not permitted. They should be disabled. Is that a release blocker, or should I just create a new issue?
2. If you have Write Access to Address but not to City or Zip, then you can move the tree within the same city or zip and save the move, but if you move it across city or zip boundaries, you cannot save. If the tree was close to the boundary, and you moved it within the boundary on the detail page but across the boundary on the map page, that could lead to the appearance of inconsistent behavior. Could this be what happened?

I'll try to reproduce #2 on my local host.

If #2 turns out to be what you were experiencing, I really don't know what to do about it. We would need to consult Scott. At the minimum, our error reporting could be vastly improved.

**Comment by RobinIsTheBird** [comment]
Created some issues:

- #2884 Move buttons are enabled when the user cannot actually move a map feature
- #2885 Authorization Exception causes a stack trace and no user message
- #2886 Logout then Save produces no message

Are any of these release blockers?

**Comment by RobinIsTheBird** [comment]
Specifics of how to reproduce the inconsistent behavior that @dboyer saw:

1. Login as a user with a role that has read only or invisible field permissions, and no Delete or Instance level permissions, but does have:
   - Add tree, tree photo, planting site
   - Write access for tree species and diameter, and for planting site stewardship
2. On the main map page, select any tree, and click Quick Edit, then Move.
3. Move the tree. Click Save. The results are documented in #2885. The changed location is not saved.
4. Cancel quick edit, and click Edit, which navigates to the detail page, Edit mode.
5. Click Move. Move the tree to another street.
6. When you click Save, the location of the planting site is updated on the map, but the Address is not updated in the Detail description.

I'll create a new issue with these steps in the description because now a user with permission _can_ move a tree in quick edit, which satisfies the original description of this issue.
