### ISSUE TITLE
Log failed API calls to Rollbar

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#2937]
To help diagnose mobile app failures like https://github.com/OpenTreeMap/otm-ios/issues/337

**Comment by RickMohr** [comment]
The failures referenced above were in fact in Rollbar, but were not logged to the OTM slack channel like many other Rollbar items are. 

For example, the timestamp on https://rollbar.com/Azavea/OpenTreeMap/items/597/occurrences/20859365635/ is `2017-01-14 09:36:17 am EST` but it didn't appear in the OTM slack channel.

Anybody know why it didn't? @jwalgran @maurizi

**Comment by maurizi** [comment]
Rollbar errors are not reported every time they occur - or else our channel would be nothing but Rollbar errors.

We report errors to the Slack channel if it is the first error of its "kind" we've seen (which is based off of the error message I believe), and otherwise only after every 10 occurrences of that kind of error.  You can also "mute" a specific error from the Rollbar page for the error.

You can see the full set of rules for notifications here: https://rollbar.com/Azavea/OpenTreeMap/settings/notifications/slack/

Since we did get a notification for the API error that caused OpenTreeMap/otm-ios#337, and the notifications seem to be working as expected, I think we can close this.

**Comment by RickMohr** [comment]
Thanks. I looked for a Rollbar module in Slack but not a Slack module in Rollbar.
