### ISSUE TITLE
Add polygon draw mode to location search

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/otm-core#2993]
Refer to the first 8 pages of the "OTM Draw Search Area v1" Marvel prototype.

Editing a polygon after it has been drawn is a separate issue.

This issue includes the implementation of the polygon draw mode, but does not include the actions after the polygon is drawn (POSTing to save the geometry and updating the filter state)

**Comment by RickMohr** [comment]
@lederer, the "custom area" drawing and editing you proposed is now live on OTM staging. 

Note it is not yet connected to searching.

Here's a summary of differences from your proposal.

Draw custom area:
* There are 3 tooltips rather than your specified 4 because Leaflet Draw doesn't support clicking a corner during drawing to remove it, and only supports 3 tooltips.
* I used the same Leaflet Draw default blue polygon style we use elsewhere in OTM. The style is customizable; if we want to change it we should also change the other places that use it (modeling scenarios and green infrastructure areas).
* We like the idea of a "spotlight/mask" effect, but it would take more work. Also one difference from MMW is that OTM allows clicking a tree dot excluded by the search (e.g. outside the custom area) so we'd want to make sure they were still visible.
* Currently to draw a custom area you click the "pencil" icon -- could we consider changing that to a "polygon" icon? I think that might make the feature more easily discoverable.

Edit Custom area:
* Leaflet Draw supports just one tooltip for editing
* Leaflet Draw doesn't support "Drag to move" for polygons or "Click an edge to add a corner". If they seem important we can roll up our sleeves.
* I did not implement "Click to Edit" -- editing a custom area seems like an uncommon operation and it would be easy to do it by mistake if we support "Click to Edit". Seems safer to stick with the pencil icon.
* Robin notes: "clicking an edge marker turns it into a vertex, spawning new edge markers, contrary to the tooltip."

**Comment by lederer** [comment]
@RickMohr Awesome. Go team.

- Now that we have a working version, I think we'll need some small adjustments to the design to help clarify the workflow when the user enters Draw mode. Stay tuned for mocks. Nothing crazy.
- Mocks will also address your points, as appropriate. Including a different "draw" icon. Totally agree.
- I think the spotlight effect is a more appropriate approach here than a polygon over the in-area trees. To generalize beyond the spotlight solution per se, any visual distinction we make between in-area trees and out-of-area trees should make the in-area ones easier to see, rather than vice versa. IIUC the spotlight solution is probably the easiest way to achieve that. (I don't expect it would stop clicks on out-of-area trees, since the current solution doesn't stop clicks on in-area trees.) How much "more work" are we talking? :)

Questions:
- Can we do `border-radius: 50%;` and `border-width: 3px;` on the vertex and edge markers?
- In "Edit custom area" mode, are we able to style the edge markers (for adding a vertex) differently from the vertex markers? I couldn't tell from the Leaflet Draw docs, and they seem to have identical classname lists in the DOM.

**Comment by dboyer** [comment]
Chiming in to say we had hoped to get this feature out by end of March, if that impacts decisions on the spotlight effect.
