### ISSUE TITLE
Integrate anonymous boundaries with search

### ISSUE THREAD

**Issue by RobinIsTheBird** [OpenTreeMap/otm-core#3019]
- Couple ajax completion from #3018 with initiating search, including advanced search parameters
- Disable polygon draw when an incompatible search is in effect, if any
- Disable incompatible search items when a polygon search is in effect, if any

Blocked on #3018

**Comment by RickMohr** [comment]
I believe this is covered by #2994. I don't think there will be any "incompatible search" issues since boundary search has none and this is just another kind of boundary search.

**Comment by jwalgran** [comment]
It is a good to ask about incompatible search. I don't think we discussed it in the design phase. What Rick said is correct. Because we are always searching features that have a geometry, boundary search will always be valid.

#2994 is intended to cover all aspect of the the integration between the frontend and backend.
