### ISSUE TITLE
OTM app NPM build errors

### ISSUE THREAD

**Issue by monroem** [OpenTreeMap/otm-core#3135]
Hi,

Unfortunately, I am struggling with the first npm build step in setting up a local OTM server from the installation guide. I am new to this. Please let me know how to fix these errors.

Thank You 

[NPM Build errors.txt](https://github.com/OpenTreeMap/otm-core/files/1019878/NPM.Build.errors.txt)

[webpack.prod.config.txt](https://github.com/OpenTreeMap/otm-core/files/1019893/webpack.prod.config.txt)
[package.txt](https://github.com/OpenTreeMap/otm-core/files/1019903/package.txt)

**Comment by maurizi** [comment]
@monroem The "package.txt" that you linked doesn't match the [`package.json`](https://github.com/OpenTreeMap/otm-core/blob/597eb2fed1fa92ec2183649ec066124477613459/package.json) for the project.

In particular, it looks like you're trying to change the project to support Webpack 2 instead of Webpack 1? (you have newer versions of some webpack plugins and are missing webpack itself in your `package.txt`).

I suggest sticking to the project's original `package.json`, as you'd have to make updates to most of the webpack configuration to update to Webpack 2.0.

If you continue to have trouble getting started, a more appropriate place than Github for help would be either our [Gitter channel](https://gitter.im/OpenTreeMap/otm-core) or [mailing list](http://groups.google.com/group/opentreemap-user).

**Comment by monroem** [comment]
Hi,
It is almost build successfully except one more error.
Please let me know.
[NPM Build errors.txt](https://github.com/OpenTreeMap/otm-core/files/1020255/NPM.Build.errors.txt)

Thank You

**Comment by jwalgran** [comment]
If you run npm list do you see leaflet.gridlayer.googlemutant@0.4.4 ?
