### ISSUE TITLE
Species search finds tree of wrong species

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-core#3145]
On [this page](https://www.opentreemap.org/phillytreemap/map/?z=20/40.02581/-75.21212&q=%7B%22species.id%22%3A%7B%22IS%22%3A%2272560%22%7D%7D) note that the search is for Allegheny Serviceberry but the dark green dot is a Japanese tree lilac.

(A friend posted to be on the lookout for edible Juneberries / Serviceberries so I tried to see where they were on `phillytreemap`.)

**Comment by maurizi** [comment]
Ok, I've got a handle on what's going on here.

There are _11_ trees at this exact same location, each with a different species (presumably testing data?).
![localhost-6060-phillytreemap-map--z 20-40 02581--75 21212 q 7b 22species id 22 3a 7b 22is 22 3a 2272560 22 7d 7d](https://user-images.githubusercontent.com/4432106/27293479-85f65520-54e4-11e7-87dd-59f13d2d2bc6.png)

![screenshot from 2017-06-19 11-45-08](https://user-images.githubusercontent.com/4432106/27293586-e1cfd11e-54e4-11e7-9a96-78f03d6f852e.png)

Our tile requests for PNGs include the search query, but our UTF Grid requests do not, so that users can still select grayed-out dots and see a popup.  The tiler _must_ pick a single feature to place in each location in the grid, and seems to have arbitrarily picked the Japanese Lilac.

This problem is compounded by the "hide-at-zoom" tiler optimization, as it will group trees in _different_ locations into the same spot on the map at higher zoom levels, which is also reflected in the UTF grid, regardless of the search.

I can see several possibilities for fixing this:
 - Have the existing UTF grid layer be filtered by the current search. This will prevent clicking on grayed-out dots, and will also harm search performance (twice the number of queries).
 - Add a new UTF grid layer above the unfiltered layer when searches are present, and forward misses from the filtered layer to the unfiltered layer.  This is more complex, and has the same performance problems as the above option, but does allow clicking the grayed-out trees.
 - Remove the UTF Grid entirely in favor of AJAX requests to the Django backend. This is simpler, and more performant when performing the search, but is slower to respond to a map click, and prevents us from showing a hand cursor when hovering over a tree dot.

**Comment by dboyer** [comment]
When we were considering some search redesign ideas, @lederer had suggested not displaying the grayed-out dots since it can be confusing when the user expects to see search results. I'm not opposed to making the grayed-out dots not clickable if it will help with this issue.

**Comment by lederer** [comment]
I've thought some more about rendering non-matching items, and reconsidered. Showing them can be useful because they're context (eg, I'm looking for that Japanese Lilac near that copse of Higan Cherries). To which end, iff we're going to show non-matches, they should remain clickable so users can interrogate them.[1]

We could minimize the immediate UX impact of the performance issues of the 2nd solution (filtered UTF grid layer atop unfiltered UTF grid layer) by doing the status-quo unfiltered search first, so the tiles are rendered and clickable right away, and then following up with the filtered search. Arguably the user is highly unlikely to click a stack of trees before the filtered search slips into place.

OTOH, as @maurizi pointed out to me, that would still double the number of queries overall and impact the product performance across users. If enough people are using it at the same time, they could feel that impact.

---
[1] Sidenote: The devil's in the details. If we had bandwidth to revisit how we render search results, I'd advocate for using size and color, rather than opacity, to differentiate them. I'd also advocate for showing their info on hover, rather than allowing them to be selectable. These changes would make them feel sufficiently different from the results, while allowing them to still serve as useful info.

**Comment by jwalgran** [comment]
We have opted to go with adding next/previous buttons to the selected map feature popup. We have used a similar disambiguation technique on other projects that which show clustered points.

<img width="1026" alt="screen shot 2017-07-13 at 10 02 45 am" src="https://user-images.githubusercontent.com/17363/28178254-a040d41a-67b2-11e7-8214-08c5f11752dd.png">

- We will keep the UTF grid, but the request to get the popup details by ID will return multiple results if there are other map features extremely close to the selected one.
- Paging through the different points in the popup must also change the details/eco shown in the right sidebar.

**Comment by lederer** [comment]
Here's a mock:
![artboard](https://user-images.githubusercontent.com/128699/28282307-fcc08fd0-6af7-11e7-9eae-e510a46d52fc.png)

Notes:
- When an infowindow represents multiple results, ensure it's always wide enough to accommodate the paging control.
- On the first (or last) item, the `prev` (or `next`) button has a transparent bg color, and is disabled. The white arrow remains visible.
- The corners of the entire paging control have the same `border-radius` as the other action buttons. IOW, the NW and SW corners of the `prev` button, and the `NE and SE` corners of the `next button`.

**Comment by dboyer** [comment]
Looks good. Thanks for the mockup.
