### ISSUE TITLE
External Link Enable/disable

### ISSUE THREAD

**Issue by nicoali** [OpenTreeMap/otm-core#3159]
if i try to enable the voice "Can View External Link" in /management/roles/

i can check on Yes but cannot save it as shown in picture attached
![bug](https://user-images.githubusercontent.com/14332128/27925513-466968bc-6285-11e7-9eb6-b715de7b13be.png)

**Comment by jwalgran** [comment]
This issue is not reproducible in my development environment or in our staging or production environments.

I suspect there is an error in the Javascript console or the server error log specific to your deployment. Please add that error to this thread https://groups.google.com/forum/#!topic/opentreemap-user/Q739GHm2Uuo

**Comment by jwalgran** [comment]
I was able to reproduce this in otm-vagrant created an issue https://github.com/OpenTreeMap/otm-vagrant/issues/52.

**Comment by nicoali** [comment]
Is there any news about this issue?

Thanks

**Comment by dboyer** [comment]
@nicoali We've scaled back development on OpenTreeMap and are generally responding to issues that impact major functionality. We don't have plans to address this issue in the immediate future.
